name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: waka_0062e56f-4ce4-4371-8686-1dbf5c695f33
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BLOCKS: "⬜🟨🟩"
